spring:
  port: 0
  application:
    name: spring-rective-mongoapi

  data:
    mongodb:
      uri: mongodb://localhost:27017,localhost:27017
      database: testdb
      repositories:
        enabled: true
